title: Avishek Das
page-top-title: Information processing in soft matter
top-section-bg-text: Dr. Avishek Das \n Postdoctoral researcher
home-subtitle: 
copyright-text: '&copy; Avishek Das 2025. All Rights Reserved.'
